// The font-metrics entry, `node scripts/ui/font-metrics.ts` (P1.21m; architecture record
// 2026-10-06-p121-token-pipeline-structure.md, points 5 and 6): reads the two web fonts and the fallback fonts'
// metrics, and writes shared/ui/tokens/font-metrics.json through the pure buildFontMetrics in shared/ui. Run it again
// only when the fonts change; font_metrics_current fails until then. Neither CI nor `npm run check` runs it.
//
// Dev dependencies (exact-pinned, MIT, generator only, never shipped):
// - @capsizecss/unpack 4.0.1 reads unitsPerEm, ascent, descent, lineGap and the latin xWidthAvg from a woff2 file
//   (dist/fs.d.mts fromFile; via fontkitten 1.0.3, whose only dependency is tiny-inflate).
// - @capsizecss/metrics 4.3.0 holds the same metrics for system fonts that are not in the repository (Arial, Courier
//   New, Roboto).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import arial from "@capsizecss/metrics/arial";
import courierNew from "@capsizecss/metrics/courierNew";
import roboto from "@capsizecss/metrics/roboto";
import { fromFile } from "@capsizecss/unpack/fs";
import { buildFontMetrics, type FallbackSpec, type FontMetrics, type WebFont } from "../../shared/ui/index.ts";

const UI = join(import.meta.dirname, "..", "..", "shared", "ui");
export const OUTPUT = "tokens/font-metrics.json";
const COMMENT =
  "Metric-adjusted local fallback faces per web font (P1.21 step 7), generated by node scripts/ui/font-metrics.ts; `sources` records the font hashes they were computed from.";

// Step 7: a desktop fallback per family, and an Android one because Android, the plan's reference device, has neither
// Arial nor Courier New. The Android mono face (local "Droid Sans Mono") waits for its metrics: they are not in
// @capsizecss/metrics, and the step book has P1.26's device pass confirm the Android names first.
const FALLBACKS: Record<string, FallbackSpec[]> = {
  "Space Grotesk": [
    { suffix: "Fallback", local: "Arial", metrics: arial },
    { suffix: "Fallback Android", local: "Roboto", metrics: roboto },
  ],
  "JetBrains Mono": [{ suffix: "Fallback", local: "Courier New", metrics: courierNew }],
};

type Sheet = { type: { fonts: { family: string; file: string }[] } };
type Source = { files: { path: string; sha256: string }[] };

/** The fallback metrics the committed fonts give, as font-metrics.json holds them. */
export async function currentFontMetrics(): Promise<FontMetrics & { $comment: string }> {
  const sheet = JSON.parse(readFileSync(join(UI, "sheet", "tokens.json"), "utf8")) as Sheet;
  const source = JSON.parse(readFileSync(join(UI, "sheet", "source.json"), "utf8")) as Source;
  const fonts: WebFont[] = [];
  for (const { family, file } of sheet.type.fonts) {
    const sha256 = source.files.find((f) => f.path === file)?.sha256;
    if (!sha256) throw new Error(`font-metrics: ${file} is not in sheet/source.json`);
    fonts.push({ family, path: file, sha256, metrics: await fromFile(join(UI, file)) });
  }
  return { $comment: COMMENT, ...buildFontMetrics(fonts, FALLBACKS) };
}

if (process.argv[1] === import.meta.filename) {
  writeFileSync(join(UI, OUTPUT), `${JSON.stringify(await currentFontMetrics(), null, 2)}\n`);
}
