// Generated by `node scripts/ui/icons.ts` from icons/icons.json (Iconoir 7.12.1); never edit.
import type { IconPaths } from "../../components/Icon/Icon.tsx";

const drawing: IconPaths = Object.freeze([
  Object.freeze({
    d: "M5 13L9 17L19 7",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
]);

export default drawing;
