// Generated by `node scripts/ui/icons.ts` from icons/icons.json (Iconoir 7.12.1); never edit.
import type { IconPaths } from "../../components/Icon/Icon.tsx";

const drawing: IconPaths = Object.freeze([
  Object.freeze({
    d: "M6 20L18 20",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
  Object.freeze({
    d: "M12 4V16M12 16L15.5 12.5M12 16L8.5 12.5",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
]);

export default drawing;
