// Generated by `node scripts/ui/icons.ts` from icons/icons.json (Iconoir 7.12.1); never edit.
import type { IconPaths } from "../../components/Icon/Icon.tsx";

const drawing: IconPaths = Object.freeze([
  Object.freeze({
    d: "M12 11.5V16.5",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
  Object.freeze({
    d: "M12 7.51L12.01 7.49889",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
  Object.freeze({
    d: "M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
]);

export default drawing;
