// Generated by `node scripts/ui/icons.ts` from icons/icons.json (Iconoir 7.12.1); never edit.
import type { IconPaths } from "../../components/Icon/Icon.tsx";

const drawing: IconPaths = Object.freeze([
  Object.freeze({
    d: "M2 10C2 10 13 10 16 10C24 10 24 21 16 21M2 10L9 3M2 10L9 17",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
]);

export default drawing;
