// Generated by `node scripts/ui/icons.ts` from icons/icons.json (Iconoir 7.12.1); never edit.
import type { IconPaths } from "../../components/Icon/Icon.tsx";

const drawing: IconPaths = Object.freeze([
  Object.freeze({
    d: "M17 17L21 21",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
  Object.freeze({
    d: "M3 11C3 15.4183 6.58172 19 11 19C13.213 19 15.2161 18.1015 16.6644 16.6493C18.1077 15.2022 19 13.2053 19 11C19 6.58172 15.4183 3 11 3C6.58172 3 3 6.58172 3 11Z",
    stroke: "currentColor",
    strokeLinecap: "round",
    strokeLinejoin: "round",
  }),
]);

export default drawing;
